fix: improve doc item typing
DS4SD/docling-core pull request #105
Opened 2024-12-12 10:31 UTC by vagenas

2024-12-12 11:49 UTC, PeterStaar-IBM commented on docling_core/types/doc/document.py
> +        KeyValueItem,
add FormItem

2024-12-12 11:51 UTC, PeterStaar-IBM requested changes
I think you forgot the FormItem in the ContentItem

2024-12-12 12:19 UTC, vagenas commented on docling_core/types/doc/document.py
> +        KeyValueItem,
Well spotted, added now.

2024-12-12 20:05 UTC, vagenas commented on docling_core/types/doc/document.py
> +    level: LevelNumber = 1
Yes, `label` is now non-overlapping — and is actually used as the discriminator field in `ContentItem` further below.

2024-12-13 10:18 UTC, dolfim-ibm reviewed
Can we easily enforce the type also in the `add_text()` method?

2024-12-13 10:33 UTC, vagenas commented
> Can we easily enforce the type also in the `add_text()` method?

Technically it will now be "enforced" when the `TextItem` is created within that method.

If you mean in terms of reflecting it to the typing of the `label` param: if we invest more efforts in that area, I would rather do it in a way that reuses the type validation of the various `DocItems`, e.g. have a single `add_node()`, but I see that as requiring some redesign, and in general outside the scope of this PR.

2024-12-13 11:45 UTC, PeterStaar-IBM approved these changes
Awesome, let's get it merged!

2024-12-13 11:48 UTC, dolfim-ibm approved these changes

2024-12-13 11:51 UTC, merged