Allow exporting a specific page to md.
DS4SD/docling-core pull request #63
Opened 2024-11-04 21:57 UTC by yasyf

2024-11-11 08:52 UTC, PeterStaar-IBM requested changes

2024-11-11 08:52 UTC, PeterStaar-IBM commented on docling_core/types/doc/document.py
> +        page_no: Optional[int] = None,
Can we have this at the end, such that people that use positional args don't run into trouble?

2024-11-11 11:41 UTC, cau-git commented
@yasyf many thanks for this contribution, we would be happy to merge it once you move the `page_no` arg to the end of the argument list of the respective methods.

2024-11-12 08:39 UTC, yasyf commented
@cau-git done!

2024-11-14 18:19 UTC, cau-git commented
@yasyf Thanks for the fixes. I have enabled the branch CI checks now. Could you please complete this by running the pre-commit toolchain (`poetry run pre-commit install`, then make another commit).

2024-11-14 22:14 UTC, yasyf commented
@cau-git done

2024-11-15 12:19 UTC, dolfim-ibm submitted a review, later dismissed
Very good. I just ran all the Docling tests locally. All green.

2024-11-17 23:41 UTC, yasyf commented
For some reason the pre-commit hook didn't run on all the files for me last time. Just ran it again and pushed @dolfim-ibm @cau-git

2024-11-18 07:53 UTC, PeterStaar-IBM approved these changes
awesome!

2024-11-18 08:04 UTC, merged